'use strict';
import mongoose from "mongoose";

const EvolveAppSchema = new mongoose.Schema({
    EvolveApp_Code: { type: 'string', required: true, unique: true, maxlength: 20 },
    EvolveApp_Name: { type: 'string', required: true },
    EvolveApp_Description: { type: 'string', default: '' },
    EvolveApp_Current_Version: { type: 'string', default: '' },
    EvolveApp_Previous_Version: { type: 'string', default: '' },
    EvolveApp_SEQ: { type: 'Number', default: '' },
    EvolveApp_Icon: { type: 'string', default: '' },
    EvolveApp_Url: { type: 'string', default: '' },
    EvolveApp_Status: { type: 'Boolean', default: false },
    EvolveMenuData: [{
        EvolveMenu_SrNo: { type: 'string', required: true, unique: true },
        EvolveMenu_Name: { type: 'string', required: true, unique: true },
        EvolveMenu_Desc: { type: 'string' },
        EvolveMenu_Url: { type: 'string' },
        EvolveMenu_IsActive: { type: 'Boolean', default: true },
        EvolveMenu_Index: { type: 'string' },
        EvolveMenu_Parent: { type: 'string' },
        EvolveMenu_AppId: { type: mongoose.Schema.Types.ObjectId, ref: 'EvolveApp' },
        EvolveMenu_IsReportPage: { type: 'Boolean' },
        EvolveUser_IframeUrl: { type: 'string' },
        EvolveMenuType_ID: { type: mongoose.Schema.Types.ObjectId, ref: 'EvolveMenuType' },
        EvolveMenu_IsUpdateExtData: { type: 'Boolean' },
        EvolveMenu_AuditEnable: { type: 'Boolean' },
        EvolveMenu_Icon: { type: 'string', default: '' },
        createdAt: { type: Date, default: Date.now },
        createdUser: { type: 'number', default: 0 },
        updatedAt: { type: Date, default: Date.now },
        updatedUser: { type: 'number', default: 0 },
        EvolveSubMenu: [{
            EvolveMenu_SrNo: { type: 'string', required: true, unique: true },
            EvolveMenu_Name: { type: 'string', required: true, unique: true },
            EvolveMenu_Desc: { type: 'string' },
            EvolveMenu_Url: { type: 'string' },
            EvolveMenu_IsActive: { type: 'Boolean', default: true },
            EvolveMenu_Index: { type: 'string' },
            EvolveMenu_Parent: { type: 'string' },
            EvolveMenu_AppId: { type: mongoose.Schema.Types.ObjectId, ref: 'EvolveApp' },
            EvolveMenu_IsReportPage: { type: 'Boolean' },
            EvolveUser_IframeUrl: { type: 'string' },
            EvolveMenuType_ID: { type: mongoose.Schema.Types.ObjectId, ref: 'EvolveMenuType' },
            EvolveMenu_IsUpdateExtData: { type: 'Boolean' },
            EvolveMenu_AuditEnable: { type: 'Boolean' },
            EvolveMenu_Icon: { type: 'string', default: '' },
            createdAt: { type: Date, default: Date.now },
            createdUser: { type: 'number', default: 0 },
            updatedAt: { type: Date, default: Date.now },
            updatedUser: { type: 'number', default: 0 },
            EvolveSubMenu: [{
                EvolveMenu_SrNo: { type: 'string', required: true, unique: true },
                EvolveMenu_Name: { type: 'string', required: true, unique: true },
                EvolveMenu_Desc: { type: 'string' },
                EvolveMenu_Url: { type: 'string' },
                EvolveMenu_IsActive: { type: 'Boolean', default: true },
                EvolveMenu_Index: { type: 'string' },
                EvolveMenu_Parent: { type: 'string' },
                EvolveMenu_AppId: { type: mongoose.Schema.Types.ObjectId, ref: 'EvolveApp' },
                EvolveMenu_IsReportPage: { type: 'Boolean' },
                EvolveUser_IframeUrl: { type: 'string' },
                EvolveMenuType_ID: { type: mongoose.Schema.Types.ObjectId, ref: 'EvolveMenuType' },
                EvolveMenu_IsUpdateExtData: { type: 'Boolean' },
                EvolveMenu_AuditEnable: { type: 'Boolean' },
                EvolveMenu_Icon: { type: 'string', default: '' },
                createdAt: { type: Date, default: Date.now },
                createdUser: { type: 'number', default: 0 },
                updatedAt: { type: Date, default: Date.now },
                updatedUser: { type: 'number', default: 0 },
                EvolveSubMenu: [{
                    EvolveMenu_SrNo: { type: 'string', required: true, unique: true },
                    EvolveMenu_Name: { type: 'string', required: true, unique: true },
                    EvolveMenu_Desc: { type: 'string' },
                    EvolveMenu_Url: { type: 'string' },
                    EvolveMenu_IsActive: { type: 'Boolean', default: true },
                    EvolveMenu_Index: { type: 'string' },
                    EvolveMenu_Parent: { type: 'string' },
                    EvolveMenu_AppId: { type: mongoose.Schema.Types.ObjectId, ref: 'EvolveApp' },
                    EvolveMenu_IsReportPage: { type: 'Boolean' },
                    EvolveUser_IframeUrl: { type: 'string' },
                    EvolveMenuType_ID: { type: mongoose.Schema.Types.ObjectId, ref: 'EvolveMenuType' },
                    EvolveMenu_IsUpdateExtData: { type: 'Boolean' },
                    EvolveMenu_AuditEnable: { type: 'Boolean' },
                    EvolveMenu_Icon: { type: 'string', default: '' },
                    createdAt: { type: Date, default: Date.now },
                    createdUser: { type: 'number', default: 0 },
                    updatedAt: { type: Date, default: Date.now },
                    updatedUser: { type: 'number', default: 0 },
                }]
            }]
        }],
    }],
    createdAt: { type: Date, default: Date.now },
    createdUser: { type: 'string', default: '' },
    updatedAt: { type: Date, default: Date.now },
    updatedUser: { type: 'string', default: '' },
},{ collection: 'EvolveApp' })
const EvolveApp = mongoose.models.EvolveApp || mongoose.model("EvolveApp", EvolveAppSchema);
export default EvolveApp;